---
# COPY this file to secrets.yml
# Do not provide any real key in this file. No keys should be pushed to GitHub
development:
  SECURE_SCHEME: HTTP
  YOUTUBE_API_KEY: <Provide key downloaded from GCP>

test:
  SECURE_SCHEME: HTTP
  YOUTUBE_API_KEY: <Provide key downloaded from GCP>

production:
  SECURE_SCHEME: HTTPS
  YOUTUBE_API_KEY: <Provide key downloaded from GCP>
