---
# COPY this file to secrets.yml
# Do not provide any real key in this file. No keys should be pushed to GitHub
SECURE_SCHEME: HTTP
YOUTUBE_API: https://www.googleapis.com/youtube/v3
YOUTUBE_API_KEY: <Provide key downloaded from GCP>
