---
# COPY this file to secrets.yml
# Do not provide any real key in this file. No keys should be pushed to Youtube
development:
  DB_FILENAME: db/local/dev.db
  SECURE_SCHEME: HTTP
  YOUTUBE_API: https://www.googleapis.com/youtube/v3
  YOUTUBE_API_KEY: <YOUTUBE_API_KEY>
  SESSION_SECRET: <GENERATED_SECRET>
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
  AWS_REGION: <AWS_REGION>
  VIDEO_QUEUE: <VIDEO_QUEUE>
  VIDEO_QUEUE_URL: <VIDEO_QUEUE_URL>

test:
  DB_FILENAME: db/local/test.db
  SECURE_SCHEME: HTTP
  YOUTUBE_API: https://www.googleapis.com/youtube/v3
  YOUTUBE_API_KEY: <YOUTUBE_API_KEY>
  SESSION_SECRET: <GENERATED_SECRET>
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
  AWS_REGION: <AWS_REGION>
  VIDEO_QUEUE: <VIDEO_QUEUE>
  VIDEO_QUEUE_URL: <VIDEO_QUEUE_URL>

production:
  DB_FILENAME:
  SECURE_SCHEME: HTTPS
  YOUTUBE_API: https://www.googleapis.com/youtube/v3
  YOUTUBE_API_KEY: <YOUTUBE_API_KEY>
  SESSION_SECRET: <GENERATED_SECRET>
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
  AWS_REGION: <AWS_REGION>
  VIDEO_QUEUE: <VIDEO_QUEUE>
  VIDEO_QUEUE_URL: <VIDEO_QUEUE_URL>
